version : '3.8'
services:
  ng:
    depends_on:
      - wp
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /wp:/var/www/html
  wp:
    depends_on:
      - db
    build: ./requirements/wordpress
    ports: 
      - "9000:9000"
    volumes:
      - /wp:/var/www/html
    environment:
      - DB_NAME=wordpress
      - DB_PASSWORD=755608
      - DB_USER=aaitbelh
      - WP_USER=aaitbelh
      - WP_PASSWORD=755608
      - WP_EMAIL=aaitbelh@example.com
  db:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/mysqldata
    environment:
      - DB_NAME=wordpress
      - DB_PASSWORD=755608
      - DB_USER=aaitbelh
