version : '3.8'
services:
  ng:
    build: ./requirements/nginx
    ports:
      - "443:443"
  wp:
    build: ./requirements/wordpress
    restart: always
  db:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"

